# Tutorial 1 - Shortest path analysis for single OD pair using Networkx

**Lesson objectives**

This tutorial focuses on **spatial networks** and learn how to construct a routable **directed** graph for Networkx and find shortest paths along the given street network based on travel times or distance by car. In addition, we will learn how to calculate travel times from a single source into all nodes in the graph. 

## Introduction to Networkx

In this tutorial we will focus on a network analysis methods that relate to way-finding. Finding a shortest path from A to B using a specific street network is a very common spatial analytics problem that has many practical applications.

Python provides easy to use tools for conducting spatial network analysis.
One of the easiest ways to start is to use a library
called [Networkx](https://networkx.github.io/documentation/stable/)
which is a Python module that provides a lot tools that can be used to
analyze networks on various different ways. It also contains algorithms
such as [Dijkstra’s
algorithm](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.shortest_paths.weighted.single_source_dijkstra.html#networkx.algorithms.shortest_paths.weighted.single_source_dijkstra)
or [A\*](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.shortest_paths.astar.astar_path.html#networkx.algorithms.shortest_paths.astar.astar_path)
algoritm that are commonly used to find shortest paths along
transportation network.

## Data and Methodology
In this part, we will learn how to do spatial network analysis in practice.

### Typical workflow for routing

If you want to conduct network analysis (in any programming language) there are a few basic steps that typically needs to be done before you can start routing. These steps are:

 1. **Retrieve data** (such as street network from OSM or Digiroad + possibly transit data if routing with PT).
 2. **Modify the network** by adding/calculating edge weights (such as travel times based on speed limit and length of the road segment).
 3. **Build a routable graph** for the routing tool that you are using (e.g. for NetworkX, igraph or OpenTripPlanner).
 4. **Conduct network analysis** (such as shortest path analysis) with the routing tool of your choice.

### 1. Retrieve data

As a first step, we need to obtain data for routing. [Pyrosm](https://pyrosm.readthedocs.io/en/latest/) library makes it really easy to retrieve routable networks from OpenStreetMap (OSM) with different transport modes (walking, cycling and driving). 

- Let's first extract OSM data for Helsinki that are walkable. In `pyrosm`, we can use a function called `osm.get_network()` which retrieves data from OpenStreetMap. It is possible to specify what kind of roads should be retrieved from OSM with `network_type` -parameter (supports `walking`, `cycling`, `driving`).

In [1]:
from pyrosm import OSM, get_data
import geopandas as gpd
import pandas as pd
import networkx as nx

# We will use test data for Helsinki that comes with pyrosm
##osm = OSM(get_data("helsinki_pbf"))
osm = OSM("data/Helsinki_larger_region.osm.pbf")

# Parse roads that can be driven by car
roads = osm.get_network(network_type="driving")
#roads.plot(figsize=(10,10))

/PUHTI_TYKKY_VhCB05H/miniconda/envs/env1/lib/python3.10/site-packages/pyrosm/networks.py:37: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  edges, nodes = prepare_geodataframe(

In [2]:
roads.head(2)

,access,area,bicycle,bridge,busway,cycleway,est_width,foot,footway,highway,...,tunnel,turn,width,id,timestamp,version,tags,osm_type,geometry,length
0,None,None,None,None,None,None,None,None,None,motorway,...,None,None,None,2293993,1522365641,21,"{""visible"":false,""light:method"":""high_pressure...",way,"MULTILINESTRING ((25.12612 60.25746, 25.12709 ...",612.0
1,None,None,no,None,None,None,None,no,None,trunk,...,None,None,None,2294195,1656446984,26,"{""visible"":false,""TEN-T"":""core"",""functional_cl...",way,"MULTILINESTRING ((25.15740 60.23955, 25.15673 ...",144.0

In [3]:
roads["oneway"].unique()

array(['yes', None, 'no'], dtype=object)

As we can see the unique values in that column are `"yes"`, `"no"` or `None`. We can use this information to construct a `directed` graph for routing by car. For walking and cycling, you typically want create a `bidirectional` graph, because the travel is typically allowed in both directions at least in Finland. Notice, that the rules vary by country, e.g. in Copenhagen you have oneway rules also for bikes but typically each road have the possibility to travel both directions (you just need to change the side of the road if you want to make a U-turn). Column `maxspeed` contains information about the speed limit for given road:

In [4]:
roads["maxspeed"].unique()

array(['100', '70', '80', '60', '40', '30', None, '50', '120', '20', '10',
       '15', '5', 'walk', '25'], dtype=object)

As we can see, there are also `None` values in the data, meaning that the speed limit has not been tagged for some roads. This is typical, and often you need to fill the non existing speed limits yourself. This can be done by taking advantage of the road class that is always present in column `highway`:

In [5]:
roads["highway"].unique()

array(['motorway', 'trunk', 'tertiary', 'residential', 'service',
       'secondary', 'unclassified', 'primary', 'cycleway',
       'motorway_link', 'trunk_link', 'primary_link', 'living_street',
       'tertiary_link', 'track', 'secondary_link', 'pedestrian',
       'footway', 'path', 'services', 'steps', 'construction',
       'rest_area', 'proposed'], dtype=object)

In [6]:
# Parse nodes and edges
nodes, edges = osm.get_network(network_type="driving", nodes=True)

In [7]:
# Check last four columns
edges.iloc[:5,-4:]

,geometry,u,v,length
0,"LINESTRING (25.12612 60.25746, 25.12709 60.25763)",286553,1393097609,56.875
1,"LINESTRING (25.12709 60.25763, 25.12800 60.25777)",1393097609,766312702,52.513
2,"LINESTRING (25.12800 60.25777, 25.12930 60.25796)",766312702,1393097450,74.826
3,"LINESTRING (25.12930 60.25796, 25.12954 60.25800)",1393097450,4118526050,13.998
4,"LINESTRING (25.12954 60.25800, 25.13060 60.25814)",4118526050,766312444,60.794

In [8]:
edges = edges.loc[~edges["highway"].isin(['cycleway', 'footway', 'pedestrian', 'trail', 'crossing'])].copy()
#edges.plot()

Now we can see, that some of the isolated edges were removed from the data. The character `~` (tilde) in the command above is a *negation* operator that is handy if you want to e.g. remove some rows from your GeoDataFrame based on criteria such as we used here.

In [9]:
# Count values
edges["maxspeed"].value_counts(dropna=False)

maxspeed
None    242504
30       91369
40       53486
50       26289
80        8378
60        5348
20        4506
100       1707
10         831
120        613
70         551
15         199
5           38
walk        16
25           9
Name: count, dtype: int64

In [10]:
edges = edges[edges.maxspeed != 'walk']
edges["maxspeed"] = edges["maxspeed"].astype(float).astype(pd.Int64Dtype())
edges["maxspeed"].unique()

<IntegerArray>
[100, 70, 80, 60, 40, 30, <NA>, 50, 120, 20, 10, 15, 5, 25]
Length: 14, dtype: Int64

In [11]:
def road_class_to_kmph(road_class):
    """
    Returns a speed limit value based on road class, 
    using typical Finnish speed limit values within urban regions.
    """
    if road_class == "motorway":
        return 100
    elif road_class == "motorway_link":
        return 80
    elif road_class in ["trunk", "trunk_link"]:
        return 60
    elif road_class == "service":
        return 30
    elif road_class == "living_street":
        return 20
    else:
        return 50

Now we can apply this function to all rows that **do not have speed limit information**:

In [12]:
# Separate rows with / without speed limit information 
mask = edges["maxspeed"].isnull()
edges_without_maxspeed = edges.loc[mask].copy()
edges_with_maxspeed = edges.loc[~mask].copy()

# Apply the function and update the maxspeed
edges_without_maxspeed["maxspeed"] = edges_without_maxspeed["highway"].apply(road_class_to_kmph)
edges_without_maxspeed.head(5).loc[:, ["maxspeed", "highway"]]

    maxspeed  highway
34        30  service
35        30  service
36        30  service
37        30  service
38        30  service

In [13]:
edges = pd.concat([edges_with_maxspeed,edges_without_maxspeed])
edges.head(-10).loc[:, ["maxspeed", "highway"]]
edges["maxspeed"].unique()

<IntegerArray>
[100, 70, 80, 60, 40, 30, 50, 120, 20, 10, 15, 5, 25]
Length: 13, dtype: Int64

In [14]:
### Check this cell with Henrikki
##edges = edges_with_maxspeed.append(edges_without_maxspeed)
##edges["maxspeed"].unique()

Great, now all of our edges have information about the speed limit. We can also visualize them:

In [15]:
# Convert the value into regular integer Series (the plotting requires having Series instead of IntegerArray) 
edges["maxspeed"] = edges["maxspeed"].astype(int)
#ax = edges.plot(column="maxspeed", figsize=(10,10), legend=True)

Finally, we can calculate the travel time in seconds using the formula we saw earlier and add that as a new cost attribute for our network:

In [16]:
edges["travel_time_seconds"] = edges["length"] / (edges["maxspeed"]/3.6)
edges.iloc[0:10, -4:]

            u           v   length  travel_time_seconds
0      286553  1393097609   56.875             2.047500
1  1393097609   766312702   52.513             1.890468
2   766312702  1393097450   74.826             2.693736
3  1393097450  4118526050   13.998             0.503928
4  4118526050   766312444   60.794             2.188584
5   766312444  5515330945   82.557             2.972052
6  5515330945      286537   16.953             0.610308
7      286537  1393097550   78.388             2.821968
8  1393097550      286536  174.982             6.299352
9   251606513  1133480099   54.846             2.820651

In [17]:
G = osm.to_graph(nodes, edges, graph_type="networkx")
G

Now we have a routable graph. `pyrosm` actually does some additional steps in the background. By default, `pyrosm` cleans all **unconnected** edges from the graph and only keeps edges that can be reached from every part of the network. In addition, `pyrosm` automatically modifies the graph attribute information in a way that they are compatible with `OSMnx` that provides many handy functionalities to work with graphs. Such as plotting an interactive map based on the graph:

In [18]:
import osmnx as ox 
### Check due to depreciation warning on 25 April
#ox.plot_graph_folium(G)
### Added due to depreciation warning on 25 April
ox.graph_to_gdfs(G, nodes=False).explore()

## Find the optimal route between two locations

Next, we will learn how to find the shortest path between two locations using [Dijkstra's](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm) algorithm.

First, let's find the closest nodes for two locations that are located in the area. OSMnx provides a handly function for geocoding an address `ox.geocode()`. We can use that to retrieve the x and y coordinates of our origin and destination.

Okay, now we have coordinates for our origin and destination.

### Find the nearest nodes

Next, we need to find the closest nodes from the graph for both of our locations. For calculating the closest point we use `ox.distance.nearest_nodes()` -function and specify `return_dist=True` to get the distance in meters.

Now we are ready to start the actual routing with NetworkX.

### Find the fastest route by distance / time

Now we can do the routing and find the shortest path between the origin and target locations
by using the `dijkstra_path()` function of NetworkX. For getting only the cumulative cost of the trip, we can directly use a function `dijkstra_path_length()` that returns the travel time without the actual path. 

With `weight` -parameter we can specify the attribute that we want to use as cost/impedance. We have now three possible weight attributes available: `'length'` and `'travel_time_seconds'`.    

- Let's first calculate the routes between locations by walking and cycling, and also retrieve the travel times

Okay, that was it! Let's now see what we got as results by visualizing the results.

For visualization purposes, we can use a handy function again from OSMnx called `ox.plot_graph_route()` (for static) or `ox.plot_route_folium()` (for interactive plot).

- Let's first make static maps

Great! Now we have successfully found the optimal route between our origin and destination and we also have estimates about the travel time that it takes to travel between the locations by walking and cycling. As we can see, the route for both travel modes is exactly the same which is natural, as the only thing that changed here was the constant travel speed.

- Let's still finally see an example how you can plot a nice interactive map out of our results with OSMnx:

In [19]:
#time_path_distance = nx.path_weight(G,time_path,weight='length')

Here we calculate the carbon emission factors for the single OD pair.


### Load and prepare the GHG emission data

Let us now import the GHG emissions per passenger-kilometer (g CO<sub>2</sub>/pkm) by transport modes Data from the file ["LCA_gCO2_per_pkm_by_transport_mode.csv"](data/LCA_gCO2_per_pkm_by_transport_mode.csv).

In [20]:
#import pandas as pd
ghg_pkm_pv = pd.read_csv("data/LCA_gCO2_per_pkm_by_transport_mode.csv",index_col=0)
ghg_pkm_pv.loc['Total_gCO2'] = ghg_pkm_pv.sum(axis=0)
ghg_pkm_pv.head()
ghg_pkm_pv.columns

Index(['Private e-scooter', 'Shared e-scooter (1st gen.)',
       'Shared e-scooter (new gen.)', 'Private bike', 'Shared bike',
       'Private e-bike', 'Shared e-bike', 'Private moped - ICE',
       'Private moped - BEV', 'Shared moped - ICE', 'Shared moped - BEV',
       'Private car - ICE', 'Private car - HEV', 'Private car - PHEV',
       'Private car - BEV', 'Private car - FCEV', 'Taxi - HEV', 'Taxi - BEV',
       'Taxi - BEV (two packs)', 'Taxi - FCEV', 'Ridesourcing - car - ICE',
       'Ridesourcing - car - HEV', 'Ridesourcing - car - PHEV',
       'Ridesourcing - car - BEV', 'Ridesourcing - car - BEV (two packs)',
       'Ridesourcing - car - FCEV', 'Bus - ICE', 'Bus - HEV', 'Bus - BEV',
       'Bus - BEV (two packs)', 'Bus - FCEV', 'Metro/urban train'],
      dtype='object')

In [21]:
## Create a dictionary of travel mode to co2 emission factors
Car_related_transit_modes = ['Private car - ICE', 'Private car - HEV', 'Private car - PHEV',
       'Private car - BEV', 'Private car - FCEV', 'Taxi - HEV', 'Taxi - BEV',
       'Taxi - BEV (two packs)', 'Taxi - FCEV']##travel_details.transport_mode.unique()
avg_CO2_emission_Car = ghg_pkm_pv.loc['Total_gCO2',Car_related_transit_modes].mean()
avg_CO2_emission_Car

155.44444444444446

In [22]:
#avg_CO2_emission_Car * time_path_distance / 1000

Now we can take our selected region and can compute shortest paths for all OD pairs in that region.

In [23]:
import pandas as pd
##import geopandas as gpd
##hexagon_df= gpd.read_file("data/Helsinki_Hexagons_with_Centroids_SelRings_9Res.csv",index_col=0, ignore_geometry=True)
loco_u_df= pd.read_csv("data/Locomizer_data/Loco_unique_Hexes_LatLon_Res9.csv",index_col=0)

# Create geometry objects from WKT strings
#hexagon_df['geometry'] = gpd.GeoSeries.from_wkt(hexagon_df['geometry'])
# Convert to GDF
#loco_u_gdf = gpd.GeoDataFrame(loco_u_df)
loco_u_df.head()
all_nearest_osmids = ox.distance.nearest_nodes(G, X=loco_u_df.lon.to_list(), Y=loco_u_df.lat.to_list())

In [24]:
loco_u_df['nearest_osm_node'] = all_nearest_osmids  #loco_u_df.apply(lambda x: ox.distance.nearest_nodes(G, X=x.lon, Y=x.lat),axis=1)

loco_u_df.to_csv("data/Locomizer_data/Loco_unique_Hexes_LatLon_Res9_nosm.csv")

In [25]:
loco_u_dict = loco_u_df.set_index('id').to_dict()
loco_u_df.head()
loco_u_dict['lat']['89089961267ffff']
loco_u_dict['lon']['89089961267ffff']
#hexagon_df_dict['89089961267ffff']
#loco_u_dict.head()
all_nearest_osmids[3:8]

[60288706, 3042393704, 2389659882, 51534023, 60289270]

In [26]:
nx.dijkstra_path_length(G, source=208801885, target=2225593683, weight='travel_time_seconds') #dict(nx.shortest_path_length(G, weight='travel_time_seconds'))
#all_SP_dict = dict(nx.shortest_path_length(G, weight='travel_time_seconds'))
#len(G.nodes())

849.1638629999999

In [27]:
from itertools import combinations, permutations

##col_combs = list(combinations(hexagon_df.Hexagon_ID, 2))
col_combs = list(permutations(loco_u_df.id, 2))
loco_u_OD_df = pd.DataFrame(col_combs,columns = [['Origin_Hexagon_ID','Destination_Hexagon_ID']])

In [28]:
loco_u_OD_df.head()

  Origin_Hexagon_ID Destination_Hexagon_ID
0   89089961267ffff        89089968003ffff
1   89089961267ffff        8908996800fffff
2   89089961267ffff        8908996801bffff
3   89089961267ffff        89089968063ffff
4   89089961267ffff        8908996806bffff

In [29]:
##hexagon_df_dict
loco_u_OD_df['Origin_Centroid_Lat'] = loco_u_OD_df.Origin_Hexagon_ID.map(lambda x: loco_u_dict['lat'][x])
#loco_u_OD_df.apply(lambda x: loco_u_dict['lat'][str(x.Origin_Hexagon_ID)],axis=1)
loco_u_OD_df['Origin_Centroid_Lon'] = loco_u_OD_df.Origin_Hexagon_ID.map(lambda x: loco_u_dict['lon'][x]) 
loco_u_OD_df['Destination_Centroid_Lat'] = loco_u_OD_df.Destination_Hexagon_ID.map(lambda x: loco_u_dict['lat'][x])
loco_u_OD_df['Destination_Centroid_Lon'] = loco_u_OD_df.Destination_Hexagon_ID.map(lambda x: loco_u_dict['lon'][x])
loco_u_OD_df['orig_node_ids'] = loco_u_OD_df.Origin_Hexagon_ID.map(lambda x: loco_u_dict['nearest_osm_node'][x])
loco_u_OD_df['dest_node_ids'] = loco_u_OD_df.Destination_Hexagon_ID.map(lambda x: loco_u_dict['nearest_osm_node'][x])
loco_u_OD_df.head()

,Origin_Hexagon_ID,Destination_Hexagon_ID,Origin_Centroid_Lat,Origin_Centroid_Lon,Destination_Centroid_Lat,Destination_Centroid_Lon,orig_node_ids,dest_node_ids
0,89089961267ffff,89089968003ffff,60.238804,24.643169,60.190132,24.725095,208801885,5851509356
1,89089961267ffff,8908996800fffff,60.238804,24.643169,60.190463,24.730225,208801885,2225593683
2,89089961267ffff,8908996801bffff,60.238804,24.643169,60.187418,24.722887,208801885,60288706
3,89089961267ffff,89089968063ffff,60.238804,24.643169,60.188410,24.738274,208801885,3042393704
4,89089961267ffff,8908996806bffff,60.238804,24.643169,60.186026,24.741193,208801885,2389659882

In [30]:
loco_u_OD_df.to_csv("data/Locomizer_data/Loco_unique_OD_Hexes_LatLon_Res9.csv")

In [ ]:
G_sp_dict = nx.floyd_warshall(G, weight='travel_time_seconds')
#G_sp_dict = dict(nx.all_pairs_shortest_path_length(G))

import json
with open('SP_G_data.json', 'w') as fp:
    json.dump(G_sp_dict, fp)
#len(all_nearest_osmids)

In [ ]:
nx.shortest_path_length(G, source=5851509356, target=2389659882, weight='travel_time_seconds')
#all_nearest_osmids[3:8]
#[208801885, 5851509356, 2225593683]
#[60288706, 3042393704, 2389659882, 51534023, 60289270]
#loco_u_OD_df['SP_length_byTime'] = loco_u_OD_df.apply(lambda x: nx.shortest_path_length(G, x.orig_node_ids, x.dest_node_ids, weight='travel_time_seconds'),axis=1)

In [ ]:
#length_dict = nx.multi_source_dijkstra_path_length(G, source=hexagon_OD_df.orig_node_ids.to_list(), target=hexagon_OD_df.dest_node_ids.to_list(), weight='travel_time_seconds')

#loco_u_OD_df['SP_length_byTime'] = loco_u_OD_df.apply(lambda x: nx.dijkstra_path_length(G, x.orig_node_ids, x.dest_node_ids, weight='travel_time_seconds'),axis=1)
#hexagon_OD_df['SP_byTime'] = hexagon_OD_df.apply(lambda x: nx.dijkstra_path(G, x.orig_node_ids, x.dest_node_ids, weight='travel_time_seconds'),axis=1)
#hexagon_OD_df['SP_length_byTime_in_meters'] =  hexagon_OD_df.apply(lambda x: nx.path_weight(G, x.SP_byTime, weight='length'),axis=1)
loco_u_OD_df['SP_length_byTime'] = loco_u_OD_df.apply(lambda x: nx.astar_path_length(G, x.orig_node_ids, x.dest_node_ids, weight='travel_time_seconds'),axis=1)
loco_u_OD_df.to_csv("data/Locomizer_data/Loco_OD_Hexes_with_SPs_ByTravelTime.csv",header=True)

In [43]:
#hexagon_OD_df.head()
loco_u_OD_df.to_csv("data/Locomizer_data/Loco_OD_Hexes_with_SPs_ByTravelTime.csv",header=True)

Here we calculate the Carbon Emission factors for all OD pairs.

In [44]:
loco_u_OD_df['ghg_co2_emission_Car'] =  loco_u_OD_df['SP_length_byTime_in_meters'] *  avg_CO2_emission_Car / 1000
loco_u_OD_df.to_csv("data/Locomizer_data/Loco_unique_Hexes_with_SPs_CarTravelTime_and_CO2emissions.csv",header=True)
loco_u_OD_df.head()

,Origin_Hexagon_ID,Destination_Hexagon_ID,Origin_Centroid_Lat,Origin_Centroid_Lon,Destination_Centroid_Lat,Destination_Centroid_Lon,orig_node_ids,dest_node_ids,SP_length_byTime,SP_byTime,SP_length_byTime_in_meters,ghg_co2_emission_Car
0,891126d33c7ffff,891126d33c3ffff,60.165104,24.93823,60.162391,24.936002,7631477466,1297416474,52.93632,"[7631477466, 7631477463, 7646215201, 763147746...",441.136,68.572140
1,891126d33c7ffff,891126d33cfffff,60.165104,24.93823,60.162714,24.941140,7631477466,7669516157,100.77960,"[7631477466, 7631477463, 7646215201, 763147746...",839.830,130.546908
2,891126d33c7ffff,891126d331bffff,60.165104,24.93823,60.165427,24.943369,7631477466,7631766115,48.19956,"[7631477466, 7631477463, 7646215201, 763147746...",401.663,62.436282
3,891126d33c7ffff,891126d3313ffff,60.165104,24.93823,60.167817,24.940459,7631477466,8874925456,184.47696,"[7631477466, 7631477463, 7646215201, 763147746...",896.080,139.290658
4,891126d33c7ffff,891126d338bffff,60.165104,24.93823,60.167495,24.935320,7631477466,9357408934,236.92608,"[7631477466, 7631477463, 7646215201, 763147746...",1578.242,245.328951

## Calculating aggregated GHG emissions due to Car trips 

### According to the locomizer data

Here, we will use the GHG emission factors for a single trip to the localizer data. Let us now recall the following data from our earlier tutorial.

In [4]:
loco_df_all = pd.read_csv(r"data/Locomizer_data/SDey_LocomizerOD_MayJune2023_R9.csv",index_col=0)
Car_share_Hsl = 0.35 ## Henkilöauto
PT_share_Hsl = 0.23 ## Joukkoliikenne
Bike_share_Hsl = 0.08  ## Polkupyörä
Walk_share_Hsl = 0.33  ## Kävely
Other_share_Hsl = 0.01 ## Muu

We aim to create a square matrix where rows and columns are the hexagon IDs of the h3 OD hexagons. The matrix entities are the total GHG emissions due to car trips according to the locomizer data.

In [15]:
hexagon_OD_df= pd.read_csv("data/Helsinki_6DHexagons_with_SPs_CarTravelTime_and_CO2emissions.csv",index_col=0)
car_OD_co2_df = hexagon_OD_df[["Origin_Hexagon_ID","Destination_Hexagon_ID","ghg_co2_emission_Car"]].set_index(["Origin_Hexagon_ID","Destination_Hexagon_ID"])
car_OD_co2_df.tail()
car_OD_co2_dict = car_OD_co2_df.to_dict()
#co2_emission_dict = {ODhex:co2_value for modes,co2_value in zip(unique_transit_modes, gross_CO2_emission_List)} 
#car_OD_co2_dict
car_OD_co2_dict['ghg_co2_emission_Car'][('891126d33c7ffff', '891126d33c3ffff')]

68.57214044444443

In [57]:
loco_df_ = loco_df_all[loco_df_all.DAY == "2023-05-28"].copy()
loco_df_May = loco_df_[loco_df_['ORIGIN_CODE_R9'] != loco_df_['DESTINATION_CODE_R9']].copy()#drop_duplicates(subset=['ORIGIN_CODE_R9','DESTINATION_CODE_R9'],keep=False)#.set_index(["ORIGIN_CODE_R9","DESTINATION_CODE_R9"])
loco_df_May.head()
#loco_df_May.apply(lambda x: print(x.ORIGIN_CODE_R9,x.DESTINATION_CODE_R9),axis=1)
x = loco_df_May.iloc[1]#["ORIGIN_CODE_R9","DESTINATION_CODE_R9"]
x.ORIGIN_CODE_R9,x.DESTINATION_CODE_R9
car_OD_co2_dict['ghg_co2_emission_Car'][(x.ORIGIN_CODE_R9,x.DESTINATION_CODE_R9)]
loco_df_May["Single_CarTrip_Co2"] = loco_df_May.apply(lambda x: car_OD_co2_dict['ghg_co2_emission_Car'][(x.ORIGIN_CODE_R9, x.DESTINATION_CODE_R9)],axis=1)
## dict[column][key] = value

In [46]:
#car_OD_co2_dict['ghg_co2_emission_Car'][('891126d06c3ffff', '891126d06c3ffff')]
'891126d14bbffff' == '891126d14bbffff'

True

In [59]:
loco_df_May["Agg_CarTrip_Co2"] = Car_share_Hsl * loco_df_May["Single_CarTrip_Co2"] * loco_df_May["EXTRAPOLATED_NUMBER_OF_USERS"]
loco_df_May.head()

,ORIGIN_CODE_R9,DESTINATION_CODE_R9,DAY,NUMBER_OF_USERS,EXTRAPOLATED_NUMBER_OF_USERS,ORIGIN_boundary,DESTINATION_boundary,interval,Single_CarTrip_Co2,Agg_CarTrip_Co2
56686,891126d06c3ffff,891126d316bffff,2023-05-28,1,109.0,POLYGON ((24.94915185444078 60.180371073684306...,POLYGON ((24.938870028200736 60.17972618869575...,1,97.997152,3738.591349
56689,891126d06c3ffff,891126d31cbffff,2023-05-28,1,109.0,POLYGON ((24.94915185444078 60.180371073684306...,POLYGON ((24.916083486601682 60.17572104750232...,1,552.389088,21073.643694
56690,891126d06c3ffff,891126d31cfffff,2023-05-28,1,109.0,POLYGON ((24.94915185444078 60.180371073684306...,"POLYGON ((24.918310763891245 60.1784342305571,...",1,609.728191,23261.130478
56719,891126d06c3ffff,891126d3307ffff,2023-05-28,1,109.0,POLYGON ((24.94915185444078 60.180371073684306...,POLYGON ((24.945371341228466 60.16984093993104...,1,208.771216,7964.621873
56747,891126d06c3ffff,891126d3313ffff,2023-05-28,1,109.0,POLYGON ((24.94915185444078 60.180371073684306...,"POLYGON ((24.93800313030377 60.16680564467473,...",1,416.290171,15881.470011

In [69]:
Total_loco_df_May = loco_df_May.groupby(['ORIGIN_CODE_R9', 'DESTINATION_CODE_R9']).agg('sum').reset_index()
Total_loco_df_May.head()

,ORIGIN_CODE_R9,DESTINATION_CODE_R9,DAY,NUMBER_OF_USERS,EXTRAPOLATED_NUMBER_OF_USERS,ORIGIN_boundary,DESTINATION_boundary,interval,Single_CarTrip_Co2,Agg_CarTrip_Co2
0,891126d06c3ffff,891126d06d3ffff,2023-05-282023-05-28,2,218.0,POLYGON ((24.94915185444078 60.180371073684306...,POLYGON ((24.944010758516768 60.18004872239447...,5,107.293352,4093.241362
1,891126d06c3ffff,891126d06dbffff,2023-05-282023-05-28,2,218.0,POLYGON ((24.94915185444078 60.180371073684306...,POLYGON ((24.946921299220385 60.17765797318835...,7,117.121171,4468.172678
2,891126d06c3ffff,891126d3023ffff,2023-05-28,1,109.0,POLYGON ((24.94915185444078 60.180371073684306...,POLYGON ((24.91676777510082 60.170618007729715...,2,455.654922,17383.235266
3,891126d06c3ffff,891126d3033ffff,2023-05-28,1,109.0,POLYGON ((24.94915185444078 60.180371073684306...,"POLYGON ((24.91163014605332 60.17029470380258,...",2,541.876691,20672.595753
4,891126d06c3ffff,891126d3067ffff,2023-05-28,1,109.0,POLYGON ((24.94915185444078 60.180371073684306...,POLYGON ((24.922589132098533 60.16583783718512...,2,436.926042,16668.728519

In [72]:
OD_loco_May = Total_loco_df_May.pivot(index='ORIGIN_CODE_R9', columns='DESTINATION_CODE_R9', values='Agg_CarTrip_Co2')
OD_loco_May.fillna("0").head(20)

DESTINATION_CODE_R9,891126d06c3ffff,891126d06cbffff,891126d06d3ffff,891126d06dbffff,891126d1483ffff,891126d1487ffff,891126d148fffff,891126d1493ffff,891126d1497ffff,891126d14a3ffff,...,891126d33b3ffff,891126d33b7ffff,891126d33bbffff,891126d33c3ffff,891126d33c7ffff,891126d33cbffff,891126d33cfffff,891126d33d3ffff,891126d33d7ffff,891126d33dbffff
ORIGIN_CODE_R9,,,,,,,,,,,,,,,,,,,,,
891126d06c3ffff,0,0,4093.241362,4468.172678,0,0,0,0,0,0,...,0,0,0,0,31019.410849,0,0,0,16056.624562,0
891126d06cbffff,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
891126d06dbffff,0,0,0,0,0,0,0,0,0,0,...,46557.972654,0,21728.024087,0,0,0,27296.783614,0,0,16960.435331
891126d1497ffff,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7729.483293
891126d14b7ffff,0,0,0,0,0,0,0,0,8003.387627,15024.531587,...,0,0,0,0,0,0,0,0,0,0
891126d14bbffff,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
891126d15d7ffff,0,89133.088793,0,0,0,0,0,0,0,0,...,0,0,0,15521.459092,26470.848305,0,13527.777356,0,29884.322064,0
891126d300bffff,25248.35422,0,0,24744.654421,0,0,0,0,0,0,...,0,0,0,0,0,0,0,14308.886241,0,0
891126d301bffff,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
891126d3023ffff,0,0,0,0,0,0,0,0,0,0,...,0,0,0,9327.845666,0,0,13060.067974,0,7524.742946,0
891126d3027ffff,0,71381.907993,0,19029.063004,0,20903.642492,22136.117112,0,38847.898924,41996.043426,...,0,0,0,0,11157.248848,27407.061716,15550.072334,0,10014.747306,0
891126d302bffff,0,0,0,0,0,0,0,0,0,0,...,0,0,27349.817442,0,0,0,0,0,0,0
891126d302fffff,0,0,0,0,0,0,0,0,35150.747852,0,...,0,0,0,0,9308.673312,0,13002.770328,0,0,0
891126d3037ffff,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,13173.008739,0,32007.679605,0,0,0
891126d3043ffff,0,0,0,0,0,0,0,0,0,0,...,0,0,18287.235801,0,0,0,0,0,9879.894432,0
891126d3047ffff,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
891126d304bffff,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
891126d304fffff,25002.920803,0,0,73497.66301,0,0,0,0,0,0,...,0,0,17827.704172,0,64519.521566,46823.883071,54210.048974,22211.887349,0,19606.635374
891126d3063ffff,0,16638.585284,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
891126d3067ffff,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [73]:
OD_loco_May.to_csv("TotalCo2_OD_Matrix_locomizer_May2024.csv",header=True)